### Курсовая работа по Python для Data Science
Студент: Мазейко Вадим

2019

### Оглавление:

1. Введение. Предмет курсовой работы.

2. Алгоритм проведения работ. Гипотезы. /УБРАТЬ

3. Подготовка данных.

4. Проверка гипотиз о значимости параметров наблюдений на искомый.

5. Создание и тестирование моделей обучения.

    5.1. модель Linear Regression.

    5.2. модель random Forest.

    5.3. Анализ результатов моделей. Выбор наилучшей модели.

6. Создание предсказания стоимости квартиры

7. Заключение

8. Тезаурус

9. Список источников

### 1. Введение.

Объктом данной курсовой работы является изучение влияния параметров наблюдений и методов построения модели на точность предсказания целевого параметра. Предметом курсовой работы является изучение взаимосвязи различнх параметров квартир и их взаимодействия с моделями предсказания для получения наиболее точных предсказаний цены

В данной работе мы пренебрегаем разницей между ценой предложения
и ценой сделки. При выполнении работы мы принимаем два неприложных условия:

1. Не допускается изменять число наблюдений путём добавления и исключения наблюдений

2. Допускается изменять, добавлять и исключать параметры наблюдений

Данные для анализа предоставлены учебным учреждением и состоят из   тренировочного массива данных train.csv с параметром цены квартиры и целевого массива данных test.csv, для которого требуется подготовить предсказание цены.

### 2. Подготовка данных.

In [2]:
import numpy as np
import pandas as pd

In [3]:
data_train = pd.read_csv('C:/Users/User/GoogleDrive/Learning/geekbrains/1_PyDC01/Kurs_project/train.csv')

In [4]:
data_train.shape

(10000, 20)

In [6]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
Id               10000 non-null int64
DistrictId       10000 non-null int64
Rooms            10000 non-null float64
Square           10000 non-null float64
LifeSquare       7887 non-null float64
KitchenSquare    10000 non-null float64
Floor            10000 non-null int64
HouseFloor       10000 non-null float64
HouseYear        10000 non-null int64
Ecology_1        10000 non-null float64
Ecology_2        10000 non-null object
Ecology_3        10000 non-null object
Social_1         10000 non-null int64
Social_2         10000 non-null int64
Social_3         10000 non-null int64
Healthcare_1     5202 non-null float64
Helthcare_2      10000 non-null int64
Shops_1          10000 non-null int64
Shops_2          10000 non-null object
Price            10000 non-null float64
dtypes: float64(8), int64(9), object(3)
memory usage: 1.5+ MB

In [11]:
# Первая вставка
data_train.loc[data_train['LifeSquare'].isna()]

,Id,DistrictId,Rooms,Square,LifeSquare,KitchenSquare,Floor,HouseFloor,HouseYear,Ecology_1,Ecology_2,Ecology_3,Social_1,Social_2,Social_3,Healthcare_1,Helthcare_2,Shops_1,Shops_2,Price
7,11993,74,2.0,80.312926,NaN,0.0,14,0.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,221244.156664
8,5172,1,2.0,64.511437,NaN,1.0,9,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,229102.795999
21,11935,27,2.0,64.711835,NaN,1.0,15,1.0,1977,0.211401,B,B,9,1892,0,NaN,0,1,B,127200.026511
23,6641,54,3.0,118.907612,NaN,0.0,2,0.0,1977,0.006076,B,B,30,5285,0,645.0,6,6,B,571069.052600
25,5073,74,2.0,82.667915,NaN,1.0,16,17.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,244145.827069
27,7550,23,2.0,64.556209,NaN,1.0,8,17.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,173910.923723
36,11703,23,1.0,41.118766,NaN,1.0,4,17.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,103510.223601
39,9371,23,2.0,60.503248,NaN,0.0,16,0.0,1977,0.034656,B,B,0,168,0,NaN,0,0,B,229778.057902
43,175,23,2.0,58.692133,NaN,1.0,16,17.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,184501.011225
46,1821,23,2.0,49.929489,NaN,1.0,9,12.0,1977,0.034656,B,B,0,168,0,NaN,0,0,B,88464.425395
54,16334,1,1.0,42.414176,NaN,1.0,14,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,156476.614348
57,3203,23,2.0,56.218702,NaN,1.0,3,3.0,1977,0.005767,B,B,1,388,0,NaN,0,0,B,90303.665683
61,4191,1,2.0,65.023899,NaN,1.0,10,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,197343.797985
63,7605,6,1.0,42.505532,NaN,1.0,6,12.0,2014,0.243205,B,B,5,1564,0,540.0,0,0,B,113617.219571
64,9723,52,2.0,64.141152,NaN,1.0,5,17.0,1977,0.371149,B,B,34,7065,1,750.0,2,5,B,158148.936484
65,11398,62,1.0,41.194188,NaN,0.0,6,0.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,114063.092041
70,10362,27,2.0,79.227049,NaN,0.0,9,0.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,167023.973143
86,9613,148,3.0,127.481583,NaN,1.0,16,1.0,2012,0.313925,B,B,22,4625,11,3855.0,2,10,B,510700.444735
98,9753,23,1.0,41.845698,NaN,1.0,14,17.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,110620.629320
103,11765,23,2.0,48.760132,NaN,1.0,3,3.0,1977,0.034656,B,B,0,168,0,NaN,0,0,B,113250.426500
104,2930,9,2.0,62.347154,NaN,1.0,6,1.0,1977,0.161532,B,B,25,5648,1,30.0,2,4,B,184172.975639
115,12377,27,2.0,60.445855,NaN,1.0,13,1.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,213798.185151
117,3975,1,2.0,65.009279,NaN,1.0,9,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,186403.484189
125,8691,1,2.0,55.233213,NaN,1.0,13,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,184324.900886
139,9742,1,2.0,63.672611,NaN,1.0,11,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,194510.147890
143,5460,74,1.0,50.145176,NaN,1.0,8,12.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,171901.087408
146,9892,62,2.0,71.304763,NaN,1.0,13,20.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,170564.408720
152,14141,23,2.0,57.699619,NaN,10.0,2,1.0,1977,0.034656,B,B,0,168,0,NaN,0,0,B,114168.532703
167,7023,1,2.0,71.005575,NaN,0.0,11,9.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,245130.106637
173,5790,27,1.0,47.177184,NaN,1.0,5,4.0,1977,0.075424,B,B,11,3097,0,NaN,0,0,B,109264.474145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9870,309,27,1.0,37.551366,NaN,1.0,11,1.0,1977,0.211401,B,B,9,1892,0,NaN,0,1,B,112877.827651
9873,55,1,2.0,65.825598,NaN,1.0,16,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,223995.669369
9880,13740,23,1.0,42.856166,NaN,1.0,13,17.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,131936.583518
9886,14495,27,2.0,76.370258,NaN,1.0,10,12.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,181589.844931
9893,1913,52,2.0,62.023753,NaN,1.0,11,17.0,2016,0.371149,B,B,34,7065,1,750.0,2,5,B,183213.528975
9908,3171,62,1.0,35.873961,NaN,0.0,25,0.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,134379.130962
9914,11428,1,2.0,69.407574,NaN,1.0,15,25.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,221718.598852
9917,1901,94,1.0,45.822669,NaN,1.0,7,1.0,1977,0.282798,B,B,33,8667,2,NaN,0,6,B,229936.748542
9923,16273,30,2.0,63.905356,NaN,1.0,6,25.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,189417.357268
9926,10680,1,1.0,41.657661,NaN,1.0,2,22.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,120424.535875
9931,13355,27,2.0,64.261856,NaN,1.0,10,1.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,223719.779293
9936,15173,30,2.0,62.341347,NaN,1.0,19,21.0,1977,0.000078,B,B,22,6398,141,1046.0,3,23,B,174256.265798
9942,9369,1,2.0,56.323990,NaN,1.0,18,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,183882.806975
9944,16160,27,2.0,60.396765,NaN,0.0,10,0.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,211810.600728
9946,4470,62,3.0,89.915337,NaN,0.0,13,15.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,191229.098911
9948,8438,1,2.0,66.736039,NaN,0.0,16,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,199237.847364
9953,5365,1,2.0,61.049491,NaN,0.0,11,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,190085.168584
9960,9307,1,2.0,57.376642,NaN,0.0,8,25.0,2016,0.007122,B,B,1,264,0,NaN,0,1,B,104450.496477
9961,1579,23,1.0,27.331108,NaN,1.0,10,12.0,1977,0.034656,B,B,0,168,0,NaN,0,0,B,60825.032060
9963,15035,1,2.0,66.547650,NaN,1.0,13,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,184050.533213
9965,6612,27,2.0,59.460685,NaN,0.0,15,19.0,1977,0.211401,B,B,9,1892,0,NaN,0,1,B,135784.320930
9972,6097,6,3.0,82.147338,NaN,1.0,17,17.0,1977,0.243205,B,B,5,1564,0,540.0,0,0,B,222068.370598
9975,5071,27,2.0,60.055527,NaN,12.0,16,15.0,1977,0.072158,B,B,2,629,1,NaN,0,0,A,190325.071232
9976,3621,22,2.0,58.853794,NaN,1.0,10,17.0,1977,0.118537,B,B,30,6207,1,1183.0,1,0,B,175229.645872
9978,13725,1,2.0,67.510526,NaN,1.0,10,17.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,185996.664227
9985,16159,27,1.0,38.968338,NaN,1.0,10,1.0,1977,0.211401,B,B,9,1892,0,NaN,0,1,B,95529.569405
9986,2996,1,2.0,64.994245,NaN,1.0,9,22.0,1977,0.007122,B,B,1,264,0,NaN,0,1,B,200332.511658
9987,15623,23,2.0,55.620092,NaN,0.0,2,4.0,1977,0.034656,B,B,0,168,0,NaN,0,0,B,115797.553006
9994,4158,23,2.0,64.864198,NaN,1.0,17,17.0,1977,0.075779,B,B,6,1437,3,NaN,0,2,B,171323.515653
9997,5123,27,1.0,47.939008,NaN,1.0,12,16.0,2015,0.072158,B,B,2,629,1,NaN,0,0,A,159143.805370